### ISSUE TITLE
Automate V&V requests

### ISSUE THREAD

**Issue by barchard** [biosensics/.github#13]
**Describe the solution you'd like**
We can automate the creation of issues of action items when a V&V is requested. We can use GitHub Actions to create issues:

https://github.com/marketplace/actions/create-an-issue

We can then assign and label the issues to the appropriate teams and open new issues after the team completes the current item. This will apply only current work that is necessary (e.g., skip server) and only when necessary (just-in-time). 

Issues should also be moved from in-progress to done when appropriate on the appropriate repo's project board.

@abbylindsay what are your thoughts? could you help us turn your checklists into a decision tree?

**Comment by barchard** [comment]
We should give this some thought and get feedback from @biosensics/operations  We shouldn't do anything until we've used the existing issues to see how things work.

**Comment by abbylindsay** [comment]
- If only server, then strike out all application items and the last two lines
- If only app, then strike out all server items
- If not an initial release, strike out all secret items (lines 2-8 in first server section)
- If V&V did not need to be created/updated, then strike out the first two lines in first ops/quality section
- If project does not include a video call feature, strike out all telehealth related items
- If no server (i.e. analyzer tool), then no parse account items
- If no sensor is involved in project, then no sensor item
